// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUT2YFCPk9HMSWjvHE9kvRF_kQ0dR3Smg',
    appId: '1:658734873245:web:1cc91339f969f8b950b274',
    messagingSenderId: '658734873245',
    projectId: 'chat-app-1c21a',
    authDomain: 'chat-app-1c21a.firebaseapp.com',
    storageBucket: 'chat-app-1c21a.appspot.com',
    measurementId: 'G-JQ8G4YC0P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDx50-VAzihTendk38NocVcJRxTihhf_Q',
    appId: '1:658734873245:android:4107e72ecbbc8beb50b274',
    messagingSenderId: '658734873245',
    projectId: 'chat-app-1c21a',
    storageBucket: 'chat-app-1c21a.appspot.com',
  );
}
